name: Node.js CI

on:
  push:
    branches: [ budget-dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/TenantAPI
          task run
